[package]
name = "modules"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
bytes = "1.4.0"
http = "0.2.9"
idna = "0.4.0"
paste = "1.0.14"
runtime = { path = "../runtime" }

derivative.workspace = true
futures.workspace = true
mozjs.workspace = true
url.workspace = true

[dependencies.ion]
path = "../ion"
features = ["macros"]

[dependencies.hyper]
version = "0.14.27"
features = ["client", "http1", "tcp"]

[dependencies.hyper-rustls]
version = "0.24.1"
default-features = false
features = ["http1", "logging", "tls12", "webpki-tokio"]

[dependencies.tokio]
workspace = true
features = ["fs"]

[dependencies.tokio-stream]
version = "0.1.14"
features = ["fs"]

[dev-dependencies.tokio]
version = "1.32.0"
features = ["macros", "rt"]

[features]
debugmozjs = ["ion/debugmozjs"]

[lib]
test = false
doctest = false
