[package]
name = "modules"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
async-fs = "1.5.0"
futures-lite = "1.12.0"
idna = "0.2.3"
ion = { path = "../ion" }
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
runtime = { path = "../runtime" }
url = "2.2.2"

[features]
debugmozjs = ["mozjs/debugmozjs", "ion/debugmozjs"]

[lib]
test = false
doctest = false
