[package]
name = "modules"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
bytes = "1.4.0"
http = "0.2.9"
hyper = { version = "0.14.26", features = ["client", "http1", "tcp"] }
hyper-rustls = { version = "0.24.0", default-features = false, features = ["http1", "logging", "tls12", "webpki-tokio"] }
idna = "0.4.0"
ion = { path = "../ion", features = ["macros"] }
paste = "1.0.12"
tokio = { workspace = true, features = ["fs"] }
tokio-stream = { version = "0.1.14", features = ["fs"] }
runtime = { path = "../runtime" }

derivative.workspace = true
futures.workspace = true
mozjs.workspace = true
url.workspace = true

[dev-dependencies]
tokio = { version = "1.28.2", features = ["macros", "rt"] }

[features]
debugmozjs = ["ion/debugmozjs"]

[lib]
test = false
doctest = false
