[package]
name = "modules"
version = "0.1.0"
authors = ["Redfire <redfire75369@hotmail.com>"]
edition = "2018"

[dependencies]
ion = { path = "../ion" }
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
runtime = { path = "../runtime" }

[features]
debugmozjs = ["mozjs/debugmozjs", "ion/debugmozjs"]
