[workspace]
members = [
	"cli",
	"ion",
	"ion-proc",
	"modules",
	"runtime",
]

[workspace.dependencies]
colored = "2.0.0"
chrono = "0.4.24"
derivative = "2.2.0"
dunce = "1.0.3"
futures = "0.3.28"
indent = "0.1.1"
mozjs = { package = "mozjs", git = "https://github.com/servo/mozjs" }
mozjs_sys = { package = "mozjs_sys", git = "https://github.com/servo/mozjs" }
once_cell = "1.17.1"
sourcemap = "6.2.3"
tokio = { version = "1.27.0", features = ["rt"] }
url = "2.3.1"
