[workspace]
members = [
	"cli",
	"ion",
	"ion-proc",
	"modules",
	"runtime",
]

[patch."https://github.com/servo/mozjs"]
mozjs_sys = { package = "mozjs_sys", git = "https://github.com/Redfire75369/mozjs", branch = "gc/root-infrastructure" }
mozjs = { package = "mozjs", git = "https://github.com/Redfire75369/mozjs", branch = "gc/root-infrastructure" }
