[workspace]
members = [
	"cli",
	"ion",
	"ion-proc",
	"modules",
	"runtime",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MPL-2.0"

[workspace.dependencies]
ion-proc = { path = "./ion-proc"}
ion = { path = "./ion"}
runtime = { path = "./runtime"}
modules = { path = "./modules"}
cli = { path = "./cli"}

arrayvec = "0.7.4"
bytes = "1.5.0"
colored = "2.1.0"
dunce = "1.0.4"
encoding_rs = "0.8.33"
futures = "0.3.30"
indent = "0.1.1"
mozjs = { package = "mozjs", git = "https://github.com/servo/mozjs" }
sourcemap = "9.0.0"
url = "2.5.0"

[workspace.dependencies.chrono]
version = "0.4.33"
default-features = false
features = ["clock", "std"]

[workspace.dependencies.tokio]
version = "1.36.0"
default-features = false

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny" # Expansion of thread_local has a #[deny]

[workspace.lints.clippy]
cast_lossless = "forbid"
clone_on_ref_ptr = "forbid"
ptr_as_ptr = "forbid"
ptr_cast_constness = "forbid"

[profile.release]
lto = "fat"
strip = "symbols"
