[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
base64-url = "1.4.13"
chrono = "0.4.22"
closure = "0.3.0"
dirs = "4.0.0"
dunce = "1.0.3"
futures = "0.3.24"
ion = { path = "../ion", features = ["macros", "sourcemap"] }
indent = "0.1.1"
indexmap = "1.9.1"
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
once_cell = "1.15.0"
os_str_bytes = "6.3.0"
sha3 = "0.10.5"
sourcemap = "6.2.0"
swc_core = { version = "0.29.14", features = ["common"] }
swc_common = { version = "0.29.5", features = ["sourcemap", "tty-emitter"] }
swc_ecmascript = { version = "0.204.12", features = ["codegen", "parser", "transforms", "typescript", "visit"] }
term-table = "1.3.2"
tokio = { version = "1.21.2", default-features = false, features = ["sync"] }
url = "2.3.1"

[features]
debugmozjs = ["ion/debugmozjs"]
promise-logger = []

[lib]
test = false
doctest = false
