[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
chrono = "0.4.19"
closure = "0.3.0"
dunce = "1.0.2"
ion = { path = "../ion" }
indent = "0.1.1"
indexmap = "1.7.0"
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
once_cell = "1.7.2"
term-table = "1.3.2"
url = "2.2.2"

[features]
debugmozjs = ["mozjs/debugmozjs", "ion/debugmozjs"]

[lib]
test = false
doctest = false
