[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
base64-url = "2.0.0"
closure = "0.3.0"
dirs = "5.0.0"
ion = { path = "../ion", features = ["macros", "sourcemap"] }
indexmap = "1.9.3"
os_str_bytes = "6.5.0"
sha3 = "0.10.7"
swc_core = { version = "0.75.15", features = ["common"] }
swc_common = { version = "0.31.3", features = ["sourcemap", "tty-emitter"] }
swc_ecmascript = { version = "0.227.10", features = ["codegen", "parser", "transforms", "typescript", "visit"] }
term-table = "1.3.2"
tokio = { version = "1.27.0", default-features = false, features = ["sync"] }

chrono.workspace = true
dunce.workspace = true
futures.workspace = true
indent.workspace = true
mozjs.workspace = true
once_cell.workspace = true
sourcemap.workspace = true
url.workspace = true

[features]
debugmozjs = ["ion/debugmozjs"]
promise-logger = []

[lib]
test = false
doctest = false
