[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
chrono = "0.4.19"
closure = "0.3.0"
dunce = "1.0.2"
ion = { path = "../ion" }
indent = "0.1.1"
indexmap = "1.8.0"
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
once_cell = "1.10.0"
swc = "0.212.0"
swc_common = { version = "0.26.0", features = ["tty-emitter"] }
swc_ecmascript = { version = "0.186.0", features = ["typescript"] }
swc_ecma_codegen = "0.120.0"
swc_ecma_parser = "0.116.0"
swc_ecma_transforms_base = "0.102.0"
swc_ecma_transforms_typescript = "0.143.0"
swc_ecma_visit = "0.75.0"
term-table = "1.3.2"
url = "2.2.2"

[features]
debugmozjs = ["ion/debugmozjs"]

[lib]
test = false
doctest = false
