[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
base64-url = "1.4.13"
chrono = "0.4.23"
closure = "0.3.0"
dirs = "4.0.0"
dunce = "1.0.3"
futures = "0.3.25"
ion = { path = "../ion", features = ["macros", "sourcemap"] }
indent = "0.1.1"
indexmap = "1.9.2"
mozjs = { package = "mozjs", git = "https://github.com/servo/mozjs" }
once_cell = "1.16.0"
os_str_bytes = "6.4.0"
sha3 = "0.10.6"
sourcemap = "6.2.0"
swc_core = { version = "0.43.23", features = ["common"] }
swc_common = { version = "0.29.14", features = ["sourcemap", "tty-emitter"] }
swc_ecmascript = { version = "0.205.90", features = ["codegen", "parser", "transforms", "typescript", "visit"] }
term-table = "1.3.2"
tokio = { version = "1.22.0", default-features = false, features = ["sync"] }
url = "2.3.1"

[features]
debugmozjs = ["ion/debugmozjs"]
promise-logger = []

[lib]
test = false
doctest = false
