[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
base64-url = "1.4.13"
chrono = "0.4.21"
closure = "0.3.0"
dirs = "4.0.0"
dunce = "1.0.2"
futures = "0.3.24"
ion = { path = "../ion", features = ["macros", "sourcemap"] }
indent = "0.1.1"
indexmap = "1.9.1"
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
once_cell = "1.13.0"
os_str_bytes = "6.2.0"
sha3 = "0.10.2"
sourcemap = "6.0.2"
swc_core = { version = "0.22.0", features = ["common"] }
swc_common = { version = "0.28.0", features = ["sourcemap", "tty-emitter"] }
swc_ecmascript = { version = "0.200.0", features = ["codegen", "parser", "transforms", "typescript", "visit"] }
term-table = "1.3.2"
url = "2.2.2"

[features]
debugmozjs = ["ion/debugmozjs"]
promise-logger = []

[lib]
test = false
doctest = false
