[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
base64 = "0.21.5"
closure = "0.3.0"
dirs = "5.0.1"
encoding_rs = "0.8.33"
form_urlencoded = "1.2.0"
indexmap = "2.1.0"
paste = "1.0.14"
sha3 = "0.10.8"
term-table = "1.3.2"

chrono.workspace = true
derivative.workspace = true
dunce.workspace = true
futures.workspace = true
indent.workspace = true
mozjs.workspace = true
sourcemap.workspace = true
url.workspace = true

[dependencies.async-recursion]
version = "1.0.5"
optional = true

[dependencies.bytes]
version = "1.5.0"
optional = true

[dependencies.const_format]
version = "0.2.32"
optional = true

[dependencies.http]
workspace = true
optional = true

[dependencies.hyper]
workspace = true
optional = true

[dependencies.hyper-rustls]
workspace = true
optional = true

[dependencies.ion]
path = "../ion"
features = ["macros", "sourcemap"]

[dependencies.mime]
version = "0.3.17"
optional = true

[dependencies.percent-encoding]
version = "2.3.0"
optional = true

[dependencies.swc_core]
version = "0.86.26"
features = [
	"common",
	"common_sourcemap",
	"common_tty",
	"ecma_ast",
	"ecma_codegen",
	"ecma_parser",
	"ecma_transforms",
	"ecma_parser_typescript",
	"ecma_transforms_typescript",
	"ecma_visit",
]

[dependencies.sys-locale]
version = "0.3.1"
optional = true

[dependencies.tokio]
workspace = true
features = ["sync"]

[features]
debugmozjs = ["ion/debugmozjs"]
fetch = [
	"dep:async-recursion",
	"dep:bytes",
	"dep:const_format",
	"dep:http",
	"dep:hyper",
	"dep:hyper-rustls",
	"dep:mime",
	"dep:percent-encoding",
	"dep:sys-locale",
]

[lib]
test = false
doctest = false
