[package]
name = "runtime"
version = "0.1.0"
authors = ["Redfire <redfire75369@hotmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
ion = { path = "../ion" }
libc = "0.2.92"
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
once_cell = "1.7.2"

[features]
debugmozjs = ["mozjs/debugmozjs", "ion/debugmozjs"]
