[package]
name = "runtime"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
base64-url = "2.0.0"
closure = "0.3.0"
dirs = "5.0.1"
encoding_rs = "0.8.33"
form_urlencoded = "1.2.0"
indexmap = "2.0.2"
mime = "0.3.17"
paste = "1.0.14"
sha3 = "0.10.8"
term-table = "1.3.2"

chrono.workspace = true
derivative.workspace = true
dunce.workspace = true
futures.workspace = true
indent.workspace = true
mozjs.workspace = true
sourcemap.workspace = true
url.workspace = true

[dependencies.bytes]
version = "1.5.0"
optional = true

[dependencies.http]
workspace = true
optional = true

[dependencies.hyper]
workspace = true
optional = true

[dependencies.hyper-rustls]
workspace = true
optional = true

[dependencies.ion]
path = "../ion"
features = ["macros", "sourcemap"]

[dependencies.swc_core]
version = "0.86.4"
features = [
	"common",
	"common_sourcemap",
	"common_tty",
	"ecma_ast",
	"ecma_codegen",
	"ecma_parser",
	"ecma_transforms",
	"ecma_parser_typescript",
	"ecma_transforms_typescript",
	"ecma_visit",
]

[dependencies.tokio]
workspace = true
features = ["sync"]

[features]
debugmozjs = ["ion/debugmozjs"]
promise-logger = []
fetch = ["dep:bytes", "dep:http", "dep:hyper", "dep:hyper-rustls"]


[lib]
test = false
doctest = false
