[package]
name = "cli"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
colored = "2.0.0"
clap = { version = "4.0.9", features = ["derive"] }
dunce = "1.0.2"
ion = { path = "../ion" }
modules = { path = "../modules" }
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
runtime = { path = "../runtime", features = ["promise-logger"] }
rustyline = "10.0.0"
rustyline-derive = "0.7.0"
tokio = { version = "1.21.2", features = ["macros", "rt"] }
sourcemap = "6.2.0"

[features]
debugmozjs = ["ion/debugmozjs"]

[[bin]]
name = "cli"
test = false
