[package]
name = "cli"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
colored = "2.0.0"
clap = { version = "3.0.12", features = ["derive"] }
ion = { path = "../ion" }
modules = { path = "../modules" }
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
runtime = { path = "../runtime" }
rustyline = "9.0.0"

[features]
debugmozjs = ["mozjs/debugmozjs", "ion/debugmozjs"]

[[bin]]
name = "cli"
test = false
