[package]
name = "ion"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
bitflags = "2.1.0"
byteorder = "1.4.3"
bytemuck = "1.13.1"
chrono = "0.4.24"
colored = "2.0.0"
derivative = "2.2.0"
futures = { version = "0.3.28", features = ["executor"] }
indent = "0.1.1"
ion-proc = { path = "../ion-proc", optional = true }
libffi = "3.2.0"
mozjs = { package = "mozjs", git = "https://github.com/servo/mozjs" }
mozjs_sys = { package = "mozjs_sys", git = "https://github.com/servo/mozjs" }
sourcemap = { version = "6.2.3", optional = true }
typed-arena = "2.0.2"
utf16string = "0.2.0"
send_wrapper = "0.6.0"

[features]
default = []
debugmozjs = ["mozjs/debugmozjs"]
macros = ["dep:ion-proc"]
sourcemap = ["dep:sourcemap"]

[lib]
doctest = false

[[test]]
name = "conversions-from-value"
path = "tests/conversions/from.rs"
[[test]]
name = "rooting"
path = "tests/rooting.rs"
[[test]]
name = "array"
path = "tests/objects/array.rs"
[[test]]
name = "date"
path = "tests/objects/date.rs"
[[test]]
name = "object"
path = "tests/objects/object.rs"

[[example]]
name = "macros"
crate-type = ["lib"]
required-features = ["macros"]
