[package]
name = "ion"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
bitflags = "2.3.2"
byteorder = "1.4.3"
bytemuck = "1.13.1"
libffi = "3.2.0"
typed-arena = "2.0.2"
utf16string = "0.2.0"
send_wrapper = "0.6.0"

colored.workspace = true
chrono.workspace = true
derivative.workspace = true
indent.workspace = true
mozjs.workspace = true
mozjs_sys.workspace = true

[dependencies.futures]
workspace = true
features = ["executor"]

[dependencies.ion-proc]
path = "../ion-proc"
optional = true

[dependencies.sourcemap]
workspace = true
optional = true

[features]
default = []
debugmozjs = ["mozjs/debugmozjs"]
macros = ["dep:ion-proc"]
sourcemap = ["dep:sourcemap"]

[lib]
doctest = false

[[test]]
name = "conversions-from-value"
path = "tests/conversions/from.rs"
[[test]]
name = "rooting"
path = "tests/rooting.rs"
[[test]]
name = "array"
path = "tests/objects/array.rs"
[[test]]
name = "date"
path = "tests/objects/date.rs"
[[test]]
name = "object"
path = "tests/objects/object.rs"

[[example]]
name = "macros"
crate-type = ["lib"]
required-features = ["macros"]
