[package]
name = "ion"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
bytemuck = "1.12.2"
chrono = "0.4.22"
colored = "2.0.0"
derivative = "2.2.0"
futures = { version = "0.3.24", features = ["executor"] }
indent = "0.1.1"
ion-proc = { path = "../ion-proc", optional = true }
libffi = "3.0.1"
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
mozjs_sys = { package = "mozjs_sys", git = "https://github.com/servo/mozjs", rev = "72ce2c95d24b225e3c87364608822b498b2312fb" }
sourcemap = { version = "6.2.0", optional = true }
typed-arena = "2.0.1"
utf16string = "0.2.0"

[features]
default = []
debugmozjs = ["mozjs/debugmozjs"]
macros = ["dep:ion-proc"]
sourcemap = ["dep:sourcemap"]

[lib]
test = false
doctest = false

[[test]]
name = "array"
path = "tests/objects/array.rs"
[[test]]
name = "date"
path = "tests/objects/date.rs"
[[test]]
name = "object"
path = "tests/objects/object.rs"

[[test]]
name = "rooting"
path = "tests/rooting.rs"

[[example]]
name = "macros"
crate-type = ["lib"]
required-features = ["macros"]
