[package]
name = "ion"
version = "0.1.0"
authors = ["Redfire <redfire75369@hotmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
libc = "0.2.92"
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
termcolor = "1.1.2"
ion-proc = { path = "../ion-proc" }

[features]
debugmozjs = ["mozjs/debugmozjs"]
