[package]
name = "ion-proc"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
convert_case = "0.6.0"
quote = "1.0.26"
prettyplease = "0.2.4"
proc-macro2 = "1.0.56"
syn = { version = "2.0.14", features = ["extra-traits", "full", "visit-mut"] }

[lib]
proc-macro = true
test = false
doctest = false
